#!/usr/bin/env python3
"""Ingest the Hero Field synthetic dataset into ADME (marielsmrttier / opendes).

Loads the flat Storage records generated by ``scripts/generate_hero_field.py``
via the Storage API (``PUT /storage/v2/records``) — the same path the Volve /
TNO master-data loaders use. Partition tokens (``osdu`` / ``<namespace>``) are
rewritten to ``opendes`` and ACL / legal are stamped at submit time.

Records carry ``tags.hero:field = Aurelia``, so the whole dataset is easy to
find and, if needed, remove later.

Prereqs: ``az login`` (token minted for https://energy.azure.com) and a prior
run of ``scripts/generate_hero_field.py``.

Usage:
    .venv/Scripts/python.exe scripts/ingest_hero_field.py            # ingest
    .venv/Scripts/python.exe scripts/ingest_hero_field.py --dry-run  # preview
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from app.models.connection import ADMEConnection, AuthMethod  # noqa: E402
from app.services.auth import (  # noqa: E402
    RefreshingTokenProvider,
    acquire_cli_token,
)
from app.services.bulk_loader import (  # noqa: E402
    DEFAULT_STORAGE_BATCH_SIZE,
    count_section_records,
    submit_records_from_paths,
)

ENDPOINT = "https://marielsmrttier.energy.azure.com"
TENANT_ID = "72f988bf-86f1-41af-91ab-2d7cd011db47"
CLIENT_ID = "ef3f6421-4b33-42b4-9184-d7c5cb2efcf2"
DATA_PARTITION_ID = "opendes"
TOKEN_RESOURCE = "https://energy.azure.com"
TOKEN_SCOPE = f"{TOKEN_RESOURCE}/.default"
LEGAL_TAG = "opendes-referencedata-legal"
ACL_OWNERS = ["data.default.owners@opendes.dataservices.energy"]
ACL_VIEWERS = ["data.default.viewers@opendes.dataservices.energy"]

DATASET_DIR = _REPO_ROOT / "app" / "data" / "datasets" / "hero-field"
SECTION = "MasterData"

# Load order (referential-friendly; Storage does not enforce it, but it keeps
# the log readable): parents first, then the components that reference them.
_MANIFESTS = [
    ("Organisations", DATASET_DIR / "master-data" / "load_Organisation.json"),
    ("Wells", DATASET_DIR / "master-data" / "load_Well.json"),
    ("Wellbores", DATASET_DIR / "master-data" / "load_Wellbore.json"),
    ("Marker sets", DATASET_DIR / "work-products" / "load_WellboreMarkerSet.json"),
    ("Documents", DATASET_DIR / "work-products" / "load_Document.json"),
]


def main() -> int:
    parser = argparse.ArgumentParser(description="Ingest the Hero Field dataset")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be loaded without contacting ADME.",
    )
    parser.add_argument(
        "--batch-size", type=int, default=DEFAULT_STORAGE_BATCH_SIZE
    )
    args = parser.parse_args()

    missing = [str(p) for _, p in _MANIFESTS if not p.is_file()]
    if missing:
        print("Missing manifest(s); run scripts/generate_hero_field.py first:")
        for path in missing:
            print("  -", path)
        return 1

    print("=" * 60)
    print(f"Hero Field ingest -> {ENDPOINT} / {DATA_PARTITION_ID}")
    print("=" * 60)

    if args.dry_run:
        total = 0
        for label, path in _MANIFESTS:
            n = count_section_records([path], SECTION)
            total += n
            print(f"  [dry-run] {label}: {n} record(s) from {path.name}")
        print("-" * 60)
        print(f"[dry-run] Would load {total} record(s). No changes made.")
        return 0

    provider = RefreshingTokenProvider(
        acquire=lambda: acquire_cli_token(resource=TOKEN_RESOURCE)
    )
    token = provider()
    connection = ADMEConnection(
        endpoint=ENDPOINT,
        tenant_id=TENANT_ID,
        client_id=CLIENT_ID,
        data_partition_id=DATA_PARTITION_ID,
        token_scope=TOKEN_SCOPE,
        auth_method=AuthMethod.USER_IMPERSONATION,
    )

    grand_ok = grand_failed = 0
    for label, path in _MANIFESTS:
        ok = failed = 0
        first_error: str | None = None
        for result in submit_records_from_paths(
            [path],
            section=SECTION,
            acl_owners=ACL_OWNERS,
            acl_viewers=ACL_VIEWERS,
            legal_tag=LEGAL_TAG,
            data_partition_id=DATA_PARTITION_ID,
            connection=connection,
            token=token,
            batch_size=args.batch_size,
            token_provider=provider,
        ):
            if result.status == "success":
                ok += 1
            else:
                failed += 1
                if first_error is None:
                    first_error = result.error
        grand_ok += ok
        grand_failed += failed
        suffix = f" (first error: {first_error})" if first_error else ""
        print(f"  {label}: ok={ok} failed={failed}{suffix}")

    print("-" * 60)
    print(f"Hero Field ingest finished: ok={grand_ok} failed={grand_failed}")
    if grand_failed == 0:
        print("Next: re-run scripts/index_markers.py to surface Aurelia")
        print("formations in the Discovery / Semantic Search experience.")
    return 1 if grand_failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
